[package]
name = "anthem"
version = "0.3.0"
authors = ["Patrick Lühne <patrick@luehne.de>"]
edition = "2018"

[dependencies]
clingo = "0.6"

[dependencies.foliage]
git = "ssh://gitea@git.luehne.de/patrick/foliage-rs.git"
branch = "refactoring"
