[package]
name = "anthem"
version = "0.3.0"
authors = ["Patrick Lühne <patrick@luehne.de>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"

[dependencies.clingo]
path = "../clingo-rs"

[dependencies.foliage]
git = "ssh://gitea@git.luehne.de/patrick/foliage-rs.git"
branch = "refactoring"
